# Build stage: pre-optimize the Keycloak JVM
# kc.sh build pre-compiles config so start --optimized boots in ~5s instead of ~60s
FROM quay.io/keycloak/keycloak:26.6 AS builder
ENV KC_DB=dev-file
ENV KC_HEALTH_ENABLED=true
RUN /opt/keycloak/bin/kc.sh build

# Runtime stage
FROM quay.io/keycloak/keycloak:26.6
COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY keycloak-realm.json /opt/keycloak/data/import/realm.json
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
