# Pre-bake the realm JSON so docker-compose doesn't need a volume mount
# The image itself is cached between CI runs to avoid re-pulling the 500MB base
FROM quay.io/keycloak/keycloak:26.6
COPY keycloak-realm.json /opt/keycloak/data/import/realm.json
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
